# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: follower

before:
  hooks:
    - go mod tidy -diff

builds:
  - id: follower
    main: ./cmd/follower
    binary: follower
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}

archives:
  - id: follower
    ids:
      - follower
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

release:
  mode: append
  replace_existing_artifacts: true

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  use: git
  sort: asc
  groups:
    - title: Breaking Changes
      regexp: '^.*!:.+$'
      order: 0
    - title: Features
      regexp: '^.*feat(\(.+\))?!?:.+$'
      order: 1
    - title: Fixes
      regexp: '^.*fix(\(.+\))?!?:.+$'
      order: 2
    - title: Other Changes
      order: 999
  filters:
    exclude:
      - '^chore:'
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
